[package]
name = "xgboost"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
forust-ml = "0.4.2"
risc0-zkvm = { version = "0.19.0", default-features = false, features = ['std'] }
rmp-serde = "1.1.2"

