[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
forust-ml = "0.4.2"
methods = { path = "../methods" }
rmp-serde = "1.1.2"
risc0-zkvm = { version = "0.19.0" }
serde = "1.0"
serde_json = "1.0.108"